project:
  type: website
  output-dir: docs

bibliography: wiki/references.bib

website:
  title: "Guidelines"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorial"
        menu:
          - wiki/Intro.md
          - wiki/Principles.md
      - text: "How-To"
        menu:
          - wiki/Workflow.md
      - text: "Explanations"
        menu:
          - wiki/Examples.md
      - text: "Reference"
        menu:
          - wiki/Syntax.md
          - Vocabulary.ipynb
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
